output "target_group_arn" {
  value       = "${aws_lb_target_group.target-group.arn}"
  description = "ARN of the load balancer target group"
}

output "lb_dns_name" {
  value       = "${aws_lb.lb.dns_name}"
  description = "The autogenerated public DNS name of the load balancer"
}